# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# | Default values
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
default_box_type            : &default_box_type             'ubuntu/xenial64'
default_box_provider        : &default_box_provider         'virtualbox'
default_box_ram             : &default_box_ram              '1024'
default_box_vram            : &default_box_vram             '128'
default_box_cpus            : &default_box_cpus             '1'
default_box_gui             : &default_box_gui              false
default_box_check_update    : &default_box_check_update     false
default_box_cpuexecutioncap : &default_box_cpuexecutioncap  '75'
default_box_uartmode1       : &default_box_uartmode1        'disconnected'
default_ssh_insert_key      : &default_ssh_insert_key       false
default_sync_folder_guest   : &default_sync_folder_guest    '.'
default_sync_folder_host    : &default_sync_folder_host     '/home/vagrant'
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
api_box_enabled             : &api_box_enabled              true
api_box_ram                 : &api_box_ram                  512
api_box_name                : &api_box_name                 'cos.api'
api_box_hostname            : &api_box_hostname             'cos.api.box'
api_box_public_ip           : &api_box_public_ip            '192.168.33.10'
api_guest_port              : &api_guest_port               '3000'
api_host_port               : &api_host_port                '3000'
api_provision               : &api_provision                'config/provision/api_provision.sh'
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
sim_box_enabled             : &sim_box_enabled              false
sim_box_ram                 : &sim_box_ram                  512
sim_box_name                : &sim_box_name                 'cos.sim'
sim_box_hostname            : &sim_box_hostname             'cos.sim.box'
sim_box_public_ip           : &sim_box_public_ip            '192.168.33.11'
sim_guest_port              : &sim_guest_port               '4000'
sim_host_port               : &sim_host_port                '4000'
sim_provision               : &sim_provision                'config/provision/sim_provision.sh'
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
bil_box_enabled             : &bil_box_enabled              false
bil_box_ram                 : &bil_box_ram                  512
bil_box_name                : &bil_box_name                 'cos.bil'
bil_box_hostname            : &bil_box_hostname             'cos.bil.box'
bil_box_public_ip           : &bil_box_public_ip            '192.168.33.12'
bil_guest_port              : &bil_guest_port               '5000'
bil_host_port               : &bil_host_port                '5000'
bil_provision               : &bil_provision                'config/provision/bil_provision.sh'
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
cache_box_enabled           : &cache_box_enabled            false
cache_box_ram               : &cache_box_ram                512
cache_box_name              : &cache_box_name               'cos.cache'
cache_box_hostname          : &cache_box_hostname           'cos.cache.box'
cache_box_public_ip         : &cache_box_public_ip          '192.168.33.13'
cache_guest_port            : &cache_guest_port             '6379'
cache_host_port             : &cache_host_port              '6379'
cache_provision             : &cache_provision              'config/provision/cache_provision.sh'
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
db_box_enabled              : &db_box_enabled               false
db_box_ram                  : &db_box_ram                   512
db_box_name                 : &db_box_name                  'cos.db'
db_box_hostname             : &db_box_hostname              'cos.db.box'
db_box_public_ip            : &db_box_public_ip             '192.168.33.14'
db_guest_port               : &db_guest_port                '27017'
db_host_port                : &db_host_port                 '27017'
db_provision                : &db_provision                 'config/provision/db_provision.sh'
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
boxes:
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# | Configure API box
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
- vm:
    name                    : *api_box_name
    provider                : *default_box_provider
    enabled                 : *api_box_enabled
    box                     : *default_box_type
    box_check_update        : *default_box_check_update
    ram                     : *api_box_ram
    vram                    : *default_box_vram
    hostname                : *api_box_hostname
    cpuexecutioncap         : *default_box_cpuexecutioncap
    uartmode1               : *default_box_uartmode1
    private_network         :
      ip                    : *api_box_public_ip
    forwarded_port          :
      - guest               : *api_guest_port
        host                : *api_host_port
      - guest               : 80
        host                : 8080
    provision               : *api_provision
    sync_folder_guest       : *default_sync_folder_guest
    sync_folder_host        : *default_sync_folder_host
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# | Configure Simulator box
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
- vm:
    name                    : *sim_box_name
    provider                : *default_box_provider
    enabled                 : *sim_box_enabled
    box                     : *default_box_type
    box_check_update        : *default_box_check_update
    ram                     : *sim_box_ram
    vram                    : *default_box_vram
    hostname                : *sim_box_hostname
    cpuexecutioncap         : *default_box_cpuexecutioncap
    uartmode1               : *default_box_uartmode1
    private_network         :
      ip                    : *sim_box_public_ip
    forwarded_port          :
      - guest               : *sim_guest_port
        host                : *sim_host_port
      - guest               : 80
        host                : 8080
    provision               : *sim_provision
    sync_folder_guest       : *default_sync_folder_guest
    sync_folder_host        : *default_sync_folder_host
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# | Configure Billing box
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
- vm:
    name                    : *bil_box_name
    provider                : *default_box_provider
    enabled                 : *bil_box_enabled
    box                     : *default_box_type
    box_check_update        : *default_box_check_update
    ram                     : *bil_box_ram
    vram                    : *default_box_vram
    hostname                : *bil_box_hostname
    cpuexecutioncap         : *default_box_cpuexecutioncap
    uartmode1               : *default_box_uartmode1
    private_network         :
      ip                    : *bil_box_public_ip
    forwarded_port          :
      - guest               : *bil_guest_port
        host                : *bil_host_port
      - guest               : 80
        host                : 8080
    provision               : *bil_provision
    sync_folder_guest       : *default_sync_folder_guest
    sync_folder_host        : *default_sync_folder_host
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# | Configure CACHE box
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
- vm:
    name                    : *cache_box_name
    provider                : *default_box_provider
    enabled                 : *cache_box_enabled
    box                     : *default_box_type
    box_check_update        : *default_box_check_update
    ram                     : *cache_box_ram
    vram                    : *default_box_vram
    hostname                : *cache_box_hostname
    cpuexecutioncap         : *default_box_cpuexecutioncap
    uartmode1               : *default_box_uartmode1
    private_network         :
      ip                    : *cache_box_public_ip
    forwarded_port          :
      - guest               : *cache_guest_port
        host                : *cache_host_port
      - guest               : 80
        host                : 8080
    provision               : *cache_provision
    sync_folder_guest       : *default_sync_folder_guest
    sync_folder_host        : *default_sync_folder_host
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# | Configure DB box
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
- vm:
    name                    : *db_box_name
    provider                : *default_box_provider
    enabled                 : *db_box_enabled
    box                     : *default_box_type
    box_check_update        : *default_box_check_update
    ram                     : *db_box_ram
    vram                    : *default_box_vram
    hostname                : *db_box_hostname
    cpuexecutioncap         : *default_box_cpuexecutioncap
    uartmode1               : *default_box_uartmode1
    private_network         :
      ip                    : *db_box_public_ip
    forwarded_port          :
      - guest               : *db_guest_port
        host                : *db_host_port
      - guest               : 80
        host                : 8080
    provision               : *db_provision
    sync_folder_guest       : *default_sync_folder_guest
    sync_folder_host        : *default_sync_folder_host
